spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onboarding_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

camunda:
  bpm:
    database:
      type: postgres
    admin-user:
      id: demo
      password: demo